### ISSUE TITLE
train.py's gradient averaging might get a list of all None's

### ISSUE THREAD

**Issue by xingyousong** [cleverhans-lab/cleverhans#1056] opened 2019-05-24 02:23 UTC
**Describe the bug**
If I use larger networks like Inception with multiple GPU's, cleverhans/train.py's avg_grads function might get a grads = [None, None, None, None...]. 

This is probably due to some of the larger networks having extra variables that are not directly useful for training. A quick fix is probably just writing in an if-statement to check if it has None's or the right shapes.

**To Reproduce**
1. Use an inception model for (I used a internal model for google, but I believe a similar model exists publicly in the tensorflow repo). 
2. Use https://github.com/tensorflow/cleverhans/blob/master/cleverhans_tutorials/mnist_tutorial_tf.py and replace the network with Inception.

**Expected behavior**
The error from using tf.add_n on a list of None's will be "ValueError: inputs must be a list of at least one Tensor/IndexedSlices with the same dtype and shape".

**System configuration**
 - OS Linux
 - Python version 3.6
 - TensorFlow version 1.x (latest)

**Comment by npapernot** [comment] 2019-06-27 03:25
Would you be able to put together a PR that implements your fix if it solved your problem? Otherwise we will have to close the issue if we don't have a way to reproduce it.

**Comment by jonasguan** [comment] 2021-01-18 16:25
Closing due to inactivity.

**Closed by jonasguan** 2021-01-18 16:25 UTC
Labels: version < 4, waiting for details
